//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 10:52:28 AM CEST 
//


package com.hs.eai.orderoverview.orderjaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderHeader">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="user">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="orderConfirmation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="shipConfirmation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Address">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="shipTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="billTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="careOf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="refNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="orderDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="totalLineItems" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="shipvia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="promoCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dataSent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PayMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="orderDetail" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lineItemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="uom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="unitPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="promoCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="invoiceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderHeader",
    "orderDetail"
})
@XmlRootElement(name = "order")
public class Order {

    @XmlElement(required = true)
    protected Order.OrderHeader orderHeader;
    protected List<Order.OrderDetail> orderDetail;

    /**
     * Gets the value of the orderHeader property.
     * 
     * @return
     *     possible object is
     *     {@link Order.OrderHeader }
     *     
     */
    public Order.OrderHeader getOrderHeader() {
        return orderHeader;
    }

    /**
     * Sets the value of the orderHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order.OrderHeader }
     *     
     */
    public void setOrderHeader(Order.OrderHeader value) {
        this.orderHeader = value;
    }

    /**
     * Gets the value of the orderDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Order.OrderDetail }
     * 
     * 
     */
    public List<Order.OrderDetail> getOrderDetail() {
        if (orderDetail == null) {
            orderDetail = new ArrayList<Order.OrderDetail>();
        }
        return this.orderDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="itemCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lineItemID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="uom" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="unitPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="promoCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="invoiceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemCode",
        "lineItemID",
        "quantity",
        "uom",
        "unitPrice",
        "promoCode",
        "invoiceType"
    })
    public static class OrderDetail {

        @XmlElement(required = true)
        protected String itemCode;
        protected int lineItemID;
        protected int quantity;
        @XmlElement(required = true)
        protected String uom;
        @XmlElement(required = true)
        protected String unitPrice;
        @XmlElement(required = true)
        protected String promoCode;
        @XmlElement(required = true)
        protected String invoiceType;

        /**
         * Gets the value of the itemCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemCode() {
            return itemCode;
        }

        /**
         * Sets the value of the itemCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemCode(String value) {
            this.itemCode = value;
        }

        /**
         * Gets the value of the lineItemID property.
         * 
         */
        public int getLineItemID() {
            return lineItemID;
        }

        /**
         * Sets the value of the lineItemID property.
         * 
         */
        public void setLineItemID(int value) {
            this.lineItemID = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         */
        public int getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(int value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the uom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUom() {
            return uom;
        }

        /**
         * Sets the value of the uom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUom(String value) {
            this.uom = value;
        }

        /**
         * Gets the value of the unitPrice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnitPrice() {
            return unitPrice;
        }

        /**
         * Sets the value of the unitPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnitPrice(String value) {
            this.unitPrice = value;
        }

        /**
         * Gets the value of the promoCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPromoCode() {
            return promoCode;
        }

        /**
         * Sets the value of the promoCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPromoCode(String value) {
            this.promoCode = value;
        }

        /**
         * Gets the value of the invoiceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInvoiceType() {
            return invoiceType;
        }

        /**
         * Sets the value of the invoiceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInvoiceType(String value) {
            this.invoiceType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="user">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="orderConfirmation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="shipConfirmation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Address">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="shipTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="billTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="careOf" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="refNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="orderDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="totalLineItems" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="shipvia" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="promoCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dataSent" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PayMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "user",
        "address",
        "po",
        "refNo",
        "orderDate",
        "totalLineItems",
        "shipvia",
        "comments",
        "promoCode",
        "dataSent",
        "payMethod"
    })
    public static class OrderHeader {

        @XmlElement(required = true)
        protected Order.OrderHeader.User user;
        @XmlElement(name = "Address", required = true)
        protected Order.OrderHeader.Address address;
        @XmlElement(name = "PO", required = true)
        protected String po;
        @XmlElement(required = true)
        protected String refNo;
        @XmlElement(required = true)
        protected String orderDate;
        protected int totalLineItems;
        @XmlElement(required = true)
        protected String shipvia;
        @XmlElement(required = true)
        protected String comments;
        @XmlElement(required = true)
        protected String promoCode;
        @XmlElement(required = true)
        protected String dataSent;
        @XmlElement(name = "PayMethod", required = true)
        protected String payMethod;

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link Order.OrderHeader.User }
         *     
         */
        public Order.OrderHeader.User getUser() {
            return user;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link Order.OrderHeader.User }
         *     
         */
        public void setUser(Order.OrderHeader.User value) {
            this.user = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link Order.OrderHeader.Address }
         *     
         */
        public Order.OrderHeader.Address getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link Order.OrderHeader.Address }
         *     
         */
        public void setAddress(Order.OrderHeader.Address value) {
            this.address = value;
        }

        /**
         * Gets the value of the po property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPO() {
            return po;
        }

        /**
         * Sets the value of the po property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPO(String value) {
            this.po = value;
        }

        /**
         * Gets the value of the refNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefNo() {
            return refNo;
        }

        /**
         * Sets the value of the refNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefNo(String value) {
            this.refNo = value;
        }

        /**
         * Gets the value of the orderDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderDate() {
            return orderDate;
        }

        /**
         * Sets the value of the orderDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderDate(String value) {
            this.orderDate = value;
        }

        /**
         * Gets the value of the totalLineItems property.
         * 
         */
        public int getTotalLineItems() {
            return totalLineItems;
        }

        /**
         * Sets the value of the totalLineItems property.
         * 
         */
        public void setTotalLineItems(int value) {
            this.totalLineItems = value;
        }

        /**
         * Gets the value of the shipvia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipvia() {
            return shipvia;
        }

        /**
         * Sets the value of the shipvia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipvia(String value) {
            this.shipvia = value;
        }

        /**
         * Gets the value of the comments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComments() {
            return comments;
        }

        /**
         * Sets the value of the comments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComments(String value) {
            this.comments = value;
        }

        /**
         * Gets the value of the promoCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPromoCode() {
            return promoCode;
        }

        /**
         * Sets the value of the promoCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPromoCode(String value) {
            this.promoCode = value;
        }

        /**
         * Gets the value of the dataSent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDataSent() {
            return dataSent;
        }

        /**
         * Sets the value of the dataSent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataSent(String value) {
            this.dataSent = value;
        }

        /**
         * Gets the value of the payMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayMethod() {
            return payMethod;
        }

        /**
         * Sets the value of the payMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayMethod(String value) {
            this.payMethod = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="shipTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="billTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="careOf" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shipTo",
            "billTo",
            "name",
            "careOf",
            "company",
            "address1",
            "address2",
            "city",
            "state",
            "zipCode",
            "country"
        })
        public static class Address {

            @XmlElement(required = true)
            protected String shipTo;
            @XmlElement(required = true)
            protected String billTo;
            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String careOf;
            @XmlElement(required = true)
            protected String company;
            @XmlElement(required = true)
            protected String address1;
            @XmlElement(required = true)
            protected String address2;
            @XmlElement(required = true)
            protected String city;
            @XmlElement(required = true)
            protected String state;
            @XmlElement(required = true)
            protected String zipCode;
            @XmlElement(required = true)
            protected String country;

            /**
             * Gets the value of the shipTo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipTo() {
                return shipTo;
            }

            /**
             * Sets the value of the shipTo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipTo(String value) {
                this.shipTo = value;
            }

            /**
             * Gets the value of the billTo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBillTo() {
                return billTo;
            }

            /**
             * Sets the value of the billTo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBillTo(String value) {
                this.billTo = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the careOf property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCareOf() {
                return careOf;
            }

            /**
             * Sets the value of the careOf property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCareOf(String value) {
                this.careOf = value;
            }

            /**
             * Gets the value of the company property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompany() {
                return company;
            }

            /**
             * Sets the value of the company property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompany(String value) {
                this.company = value;
            }

            /**
             * Gets the value of the address1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress1() {
                return address1;
            }

            /**
             * Sets the value of the address1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress1(String value) {
                this.address1 = value;
            }

            /**
             * Gets the value of the address2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress2() {
                return address2;
            }

            /**
             * Sets the value of the address2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress2(String value) {
                this.address2 = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the state property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getState() {
                return state;
            }

            /**
             * Sets the value of the state property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setState(String value) {
                this.state = value;
            }

            /**
             * Gets the value of the zipCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZipCode() {
                return zipCode;
            }

            /**
             * Sets the value of the zipCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZipCode(String value) {
                this.zipCode = value;
            }

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="orderConfirmation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="shipConfirmation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "guid",
            "email",
            "orderConfirmation",
            "shipConfirmation",
            "type"
        })
        public static class User {

            @XmlElement(required = true)
            protected String guid;
            @XmlElement(required = true)
            protected String email;
            @XmlElement(required = true)
            protected String orderConfirmation;
            @XmlElement(required = true)
            protected String shipConfirmation;
            protected int type;

            /**
             * Gets the value of the guid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGuid() {
                return guid;
            }

            /**
             * Sets the value of the guid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGuid(String value) {
                this.guid = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

            /**
             * Gets the value of the orderConfirmation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrderConfirmation() {
                return orderConfirmation;
            }

            /**
             * Sets the value of the orderConfirmation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrderConfirmation(String value) {
                this.orderConfirmation = value;
            }

            /**
             * Gets the value of the shipConfirmation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShipConfirmation() {
                return shipConfirmation;
            }

            /**
             * Sets the value of the shipConfirmation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShipConfirmation(String value) {
                this.shipConfirmation = value;
            }

            /**
             * Gets the value of the type property.
             * 
             */
            public int getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             */
            public void setType(int value) {
                this.type = value;
            }

        }

    }

}
